config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'

  resources :reports
  resources :leaderboard

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :report

  mount_uploader :attachment, AttachmentUploader
end

app/models/report.rb
class Report < ActiveRecord::Base
  scope :valid_reports, -> { where(is_valid: true) }
  scope :from_mention, -> { where(source: "mention") }
  scope :from_hashtag, -> { where(source: "search") }
  has_many :images
  belongs_to :user

  def tweet_to_invalid_report(tweet)
    TWITTER.update("@#{tweet.user.screen_name} Para reportar un infractor,"\
                   "necesitas una imagen y geolocalizar el tweet. Para mas"\
                   "informacion: http://placeholder.com", in_reply_to_status: tweet)
  end

  def attach_images(tweet)
    urls = get_images_url(tweet)
    urls.each do |url|
      self.images.build(remote_attachment_url: url.to_s)
    end
  end

  def get_images_url(tweet)
    return tweet.images.map(&:media_url)
  end
end

app/models/report_builder.rb
class ReportBuilder

  def self.create_reports(tweets, source)
    tweets.each do |tweet|
      adapted_tweet = TweetAdapter.new(tweet)
      report = self.find_or_initialize_base_report(adapted_tweet, source)
      return if !report.new_record?
      if adapted_tweet.valid?
        self.create_valid_report(adapted_tweet, report)
      else
        report.save
        # report.tweet_to_invalid_report(tweet)
      end
    end
  end

  def self.create_valid_report(tweet, report)
    user = User.create_or_update_name(tweet.user)
    report.save
    report.attach_images(tweet)
    report.update_attributes(is_valid: true, user_id: user.id)
  end

  def self.find_or_initialize_base_report(tweet, source)
    # Report.new(self.tweet_params(tweet))
    Report.create_with(self.tweet_params(tweet, source)).find_or_initialize_by(tweet_id: tweet.id)
  end

  def self.tweet_params(tweet, source)
    params = {}
    params[:tweet_id] = tweet.id
    params[:latitude] = tweet.latitude
    params[:longitude] = tweet.longitude
    params[:post] = tweet.post
    params[:source] = source
    return params
  end
end

app/models/tweet_adapter.rb
class TweetAdapter

  def initialize(tweet)
    @tweet = tweet
  end

  def valid?
    !self.latitude.nil? && !self.longitude.nil? && self.has_images?
  end

  def latitude
    @tweet.geo.coordinates.first
  end

  def longitude
    @tweet.geo.coordinates.last
  end

  def id
    @tweet.id
  end

  def post
    @tweet.text
  end

  def has_images?
    !self.images.empty?
  end

  def images
    @tweet.media.select{ |media| media.instance_of?(Twitter::Media::Photo) }
  end

  def user
    @tweet.user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reports

  def self.create_or_update_name(user)
    found_user = User.create_with(account_name: user.screen_name).find_or_create_by(account_id: user.id)
    if found_user.account_name != user.screen_name
      found_user.update_attribute(:account_name, user.screen_name)
    end
    found_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  before_filter :sort_users

  def index
    @users
  end

  private
    def sort_users
      @users = User.all.sort_by { |user| user.reports.count }.reverse!
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :load_report, only: [:show]
  before_filter :load_images, only: [:show]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.valid_reports
    @hash = Gmaps4rails.build_markers(@reports) do |report, marker|
      marker.lat report.latitude
      marker.lng report.longitude
      marker.infowindow report.post
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @hash = Gmaps4rails.build_markers(@report) do |report, marker|
      marker.lat report.latitude
      marker.lng report.longitude
      marker.infowindow report.post
    end
  end

  private

    def load_report
      @report = Report.find(params[:id])
    end

    def load_images
      @images = @report.images
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Infractores</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leaderboard/index.html.erb
<h1>Leading Board</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>User</th>
      <th>Reports</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td>#<%= index + 1 %></td>
        <td>@<%= user.account_name %></td>
        <td><%= user.reports.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', reports_path %>

app/views/reports/_map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({
      provider: {
        disableDefaultUI: true
      },
      internal: {
        id: 'map'
      }
    },
    function(){
      markers = handler.addMarkers(<%=raw hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    }
  );
</script>

app/views/reports/index.html.erb
<h1>Listing Reports</h1>

<%= render partial: "map", locals: { hash: @hash } %>
<%= link_to "Leader Board", leaderboard_index_url %>
<table>
  <thead>
    <tr>
      <th colspan="1"></th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= image_tag report.images.first.attachment.medium %></td>
        <td><%= report.post %></td>
        <td>@<%= report.user.account_name %></td>
        <td><%= link_to 'Show', report %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/show.html.erb
<table>
  <tr>
    <% @images.each do |image| %>
      <td><%= image_tag image.attachment.large %></td>
    <% end %>
  </tr>
</table>

<table>
  <tr>
    <td><p><%= @report.post %></p></td>
    <td><p>@<%= @report.user.account_name %></p></td>
  </tr>
</table>

<%= render partial: "map", locals: { hash: @hash } %>

<%= link_to 'Back', reports_path %>